/*
---
keep: false
---
Generated by /Users/nielsgregersjohansen/kitchens/365admin-publish/scaffold/25-generatedatabase.ps1
Do not edit this file manually
*/

drop schema if exists "proc" cascade;

CREATE SCHEMA "proc";{{ template "bite_create_proc.sql".}} 
{{ template "bite_update_proc.sql".}} 
{{ template "bite_delete_proc.sql".}} 
{{ template "bite_undo_delete_proc.sql".}} 
{{ template "auditlog_create_proc.sql".}} 
{{ template "auditlog_update_proc.sql".}} 
{{ template "auditlog_delete_proc.sql".}} 
{{ template "auditlog_undo_delete_proc.sql".}} 

